/*
 * File: MicrogridNode.cs
 * Purpose: Domain entity for a solar microgrid hub/node - GPS location, capacity, battery slots
 *          and its daily operating schedule.
 * Project: Smart Solar Microgrid Trading System - Web Service (SolarGrid API)
 * Module: SE4040 Enterprise Application Development - Assignment 1
 */

namespace SolarGrid.Domain.Entities
{
    public class MicrogridNode
    {
        // Generated by the database on insert.
        public string Id { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;
        public double Latitude { get; set; }
        public double Longitude { get; set; }

        // Capacity in kW/h, per assignment spec.
        public double CapacityKWh { get; set; }

        // Number of available battery storage slots at this node (Grid Operators keep this current).
        public int BatterySlots { get; set; }

        // Operating schedule in Sri Lanka local time, "HH:mm". Null means open around the clock.
        public string? OpenTime { get; set; }
        public string? CloseTime { get; set; }

        // False once deactivated; blocked by ReservationPolicy while live reservations exist.
        public bool IsActive { get; set; } = true;
    }
}
