/*
 * File: CircumIcons.kt
 * Purpose: The app's icon set - Circum Icons (same set as the web app), shipped as vector
 *          drawables in res/drawable/ci_*.xml (generated by scripts/generate-android-icons.mjs).
 *          Use like Material icons: Icon(CircumIcons.Back, contentDescription = "Back").
 * Project: Smart Solar Microgrid Trading System - Android App
 * Module: SE4040 Enterprise Application Development - Assignment 1
 */

package com.solargrid.app.ui.common

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.vectorResource
import com.solargrid.app.R

object CircumIcons {
    val Alert: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_alert)
    val Back: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_back)
    val Calendar: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_calendar)
    val Check: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_check)
    val ChevronDown: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_chevron_down)
    val Clock: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_clock)
    val List: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_list)
    val Logout: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_logout)
    val Map: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_map)
    val Node: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_node)
    val Plus: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_plus)
    val Remove: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_remove)
    val Repeat: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_repeat)
    val Scan: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_scan)
    val Sun: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_sun)
    val Timer: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_timer)
    val User: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ci_user)
}
