/*
 * File: MicrogridNode.cs
 * Purpose: Data model for a solar microgrid hub/node - GPS location, capacity, battery slots.
 * Project: Smart Solar Microgrid Trading System - Web Service (SolarGrid API)
 * Module: SE4040 Enterprise Application Development - Assignment 1
 */

using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace SolarGrid.Models
{
    public class MicrogridNode
    {
        // Auto-generated by MongoDB on insert; represented as a string in C#.
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;
        public double Latitude { get; set; }
        public double Longitude { get; set; }

        // Capacity in kW/h, per assignment spec.
        public double CapacityKWh { get; set; }

        // Number of available battery storage slots at this node.
        public int BatterySlots { get; set; }

        // False once deactivated; deactivation is blocked in the service layer if active reservations exist.
        public bool IsActive { get; set; } = true;
    }
}
